import * as db from './db';
import { Player, Team, AuctionRules, DEFAULT_RULES } from './types';
import { forgetRoom } from './roomManager';

export const DEMO_ROOM_ID = 'DEMO';
export const DEMO_ADMIN_TOKEN = 'demo_admin_secret';

export const DEMO_TEAMS: Team[] = [
  {
    id: 'team_mt',
    name: 'Mumbai Titans',
    code: 'MT',
    purse: 12000,
    originalPurse: 12000,
    rtmCards: 2,
    rosterIds: [],
    token: 'tok_mt',
  },
  {
    id: 'team_csk',
    name: 'Chennai Kings',
    code: 'CSK',
    purse: 11000,
    originalPurse: 11000,
    rtmCards: 2,
    rosterIds: [],
    token: 'tok_csk',
  },
  {
    id: 'team_blr',
    name: 'Bangalore Strikers',
    code: 'BLR',
    purse: 10500,
    originalPurse: 10500,
    rtmCards: 2,
    rosterIds: [],
    token: 'tok_blr',
  },
  {
    id: 'team_del',
    name: 'Delhi Dynamos',
    code: 'DEL',
    purse: 9800,
    originalPurse: 9800,
    rtmCards: 1,
    rosterIds: [],
    token: 'tok_del',
  },
  {
    id: 'team_kkr',
    name: 'Kolkata Crusaders',
    code: 'KKR',
    purse: 10000,
    originalPurse: 10000,
    rtmCards: 2,
    rosterIds: [],
    token: 'tok_kkr',
  },
];

export const DEMO_PLAYERS: Player[] = [
  // --- BATSMEN ---
  {
    id: 'p_virat',
    name: 'Virat Sharma',
    role: 'Batsman',
    basePrice: 200,
    status: 'available',
    previousTeamCode: 'BLR',
    matches: 242,
    runs: 7850,
    average: 38.8,
    strikeRate: 133.5,
    cricheroesStats: { 'Innings': '234', '50s/100s': '55/8', 'High Score': '113*', 'Boundary %': '58.2%' },
  },
  {
    id: 'p_rohit',
    name: 'Rohit Verma',
    role: 'Batsman',
    basePrice: 200,
    status: 'available',
    previousTeamCode: 'MT',
    matches: 250,
    runs: 6450,
    average: 30.2,
    strikeRate: 131.2,
    cricheroesStats: { 'Innings': '245', '50s/100s': '43/2', 'High Score': '109*', 'Sixes': '275' },
  },
  {
    id: 'p_surya',
    name: 'Suryakumar Yadav',
    role: 'Batsman',
    basePrice: 200,
    status: 'available',
    previousTeamCode: 'MT',
    matches: 145,
    runs: 3500,
    average: 33.6,
    strikeRate: 172.4,
    cricheroesStats: { 'Innings': '132', '360° Shots': '42%', 'Strike Rate PP': '145.2', 'Death SR': '210.5' },
  },
  {
    id: 'p_shubman',
    name: 'Shubman Gill',
    role: 'Batsman',
    basePrice: 150,
    status: 'available',
    previousTeamCode: 'DEL',
    matches: 98,
    runs: 3200,
    average: 41.5,
    strikeRate: 137.8,
    cricheroesStats: { 'Innings': '98', 'Orange Caps': '1', 'High Score': '129', 'Dot Ball %': '31.4%' },
  },
  {
    id: 'p_jaiswal',
    name: 'Yashasvi Jaiswal',
    role: 'Batsman',
    basePrice: 150,
    status: 'available',
    previousTeamCode: 'BLR',
    matches: 55,
    runs: 1850,
    average: 34.2,
    strikeRate: 154.6,
    cricheroesStats: { 'Innings': '55', 'Powerplay SR': '168.2', 'Fastest 50': '13 balls', 'Boundary %': '64.1%' },
  },
  {
    id: 'p_rinku',
    name: 'Rinku Singh',
    role: 'Batsman',
    basePrice: 100,
    status: 'available',
    previousTeamCode: 'KKR',
    matches: 48,
    runs: 950,
    average: 36.5,
    strikeRate: 151.0,
    cricheroesStats: { 'Finishes': '14', 'Death Over SR': '194.2', 'Last Over Wins': '4' },
  },

  // --- BOWLERS ---
  {
    id: 'p_bumrah',
    name: 'Jasprit Bumrah',
    role: 'Bowler',
    basePrice: 200,
    status: 'available',
    previousTeamCode: 'MT',
    matches: 130,
    wickets: 165,
    average: 22.8,
    economy: 7.39,
    cricheroesStats: { 'Overs': '495', 'Dot Balls': '1240', 'Death Economy': '7.85', 'Best': '5/10' },
  },
  {
    id: 'p_rashid',
    name: 'Rashid Khan',
    role: 'Bowler',
    basePrice: 200,
    status: 'available',
    previousTeamCode: 'DEL',
    matches: 118,
    wickets: 145,
    average: 20.4,
    economy: 6.78,
    cricheroesStats: { 'Overs': '465', 'Middle Overs Econ': '6.22', 'Strike Rate': '19.2' },
  },
  {
    id: 'p_shami',
    name: 'Mohammed Shami',
    role: 'Bowler',
    basePrice: 150,
    status: 'available',
    previousTeamCode: 'KKR',
    matches: 112,
    wickets: 132,
    average: 24.1,
    economy: 8.21,
    cricheroesStats: { 'PP Wickets': '48', 'Purple Caps': '1', 'Best': '4/11' },
  },
  {
    id: 'p_boult',
    name: 'Trent Boult',
    role: 'Bowler',
    basePrice: 150,
    status: 'available',
    previousTeamCode: 'CSK',
    matches: 92,
    wickets: 110,
    average: 25.4,
    economy: 8.12,
    cricheroesStats: { 'First Over Wickets': '26', 'Dot Ball %': '48.5%' },
  },
  {
    id: 'p_kuldeep',
    name: 'Kuldeep Yadav',
    role: 'Bowler',
    basePrice: 120,
    status: 'available',
    previousTeamCode: 'DEL',
    matches: 85,
    wickets: 98,
    average: 23.5,
    economy: 7.65,
    cricheroesStats: { 'LHB Avg': '19.2', 'RHB Avg': '24.1', 'Best': '4/14' },
  },
  {
    id: 'p_arshdeep',
    name: 'Arshdeep Singh',
    role: 'Bowler',
    basePrice: 100,
    status: 'available',
    previousTeamCode: 'KKR',
    matches: 65,
    wickets: 76,
    average: 26.2,
    economy: 8.55,
    cricheroesStats: { 'Death Overs': '72', 'Yorker %': '38.2%' },
  },

  // --- ALL-ROUNDERS ---
  {
    id: 'p_hardik',
    name: 'Hardik Pandya',
    role: 'All-Rounder',
    basePrice: 200,
    status: 'available',
    previousTeamCode: 'MT',
    matches: 135,
    runs: 2450,
    wickets: 62,
    average: 29.8,
    strikeRate: 147.2,
    economy: 8.75,
    cricheroesStats: { 'Bat SR Death': '182.5', 'Wickets PP': '18', 'Catches': '65' },
  },
  {
    id: 'p_jadeja',
    name: 'Ravindra Jadeja',
    role: 'All-Rounder',
    basePrice: 200,
    status: 'available',
    previousTeamCode: 'CSK',
    matches: 228,
    runs: 2850,
    wickets: 158,
    average: 27.5,
    strikeRate: 129.8,
    economy: 7.62,
    cricheroesStats: { 'Direct Hits': '28', 'Catches': '104', 'Economy Spin': '7.12' },
  },
  {
    id: 'p_russell',
    name: 'Andre Russell',
    role: 'All-Rounder',
    basePrice: 180,
    status: 'available',
    previousTeamCode: 'KKR',
    matches: 115,
    runs: 2380,
    wickets: 98,
    strikeRate: 174.5,
    economy: 9.15,
    cricheroesStats: { 'Death SR': '208.5', 'Best Bowling': '5/15', 'Boundary Rate': '4.1 balls' },
  },
  {
    id: 'p_maxwell',
    name: 'Glenn Maxwell',
    role: 'All-Rounder',
    basePrice: 150,
    status: 'available',
    previousTeamCode: 'BLR',
    matches: 126,
    runs: 2720,
    wickets: 36,
    strikeRate: 157.8,
    economy: 8.35,
    cricheroesStats: { 'Spin SR': '178.4', 'Reverse Sweep %': '22%' },
  },
  {
    id: 'p_axar',
    name: 'Axar Patel',
    role: 'All-Rounder',
    basePrice: 120,
    status: 'available',
    previousTeamCode: 'DEL',
    matches: 142,
    runs: 1620,
    wickets: 118,
    average: 21.4,
    strikeRate: 132.5,
    economy: 7.24,
    cricheroesStats: { 'Bat Avg No.7': '32.1', 'Econ Middle': '6.95' },
  },
  {
    id: 'p_curran',
    name: 'Sam Curran',
    role: 'All-Rounder',
    basePrice: 120,
    status: 'available',
    previousTeamCode: 'CSK',
    matches: 58,
    runs: 820,
    wickets: 52,
    strikeRate: 135.4,
    economy: 8.95,
    cricheroesStats: { 'Powerplay Econ': '7.8', 'Best': '4/11' },
  },

  // --- WICKETKEEPERS ---
  {
    id: 'p_dhoni',
    name: 'MS Dhoni',
    role: 'Wicketkeeper',
    basePrice: 150,
    status: 'available',
    previousTeamCode: 'CSK',
    matches: 260,
    runs: 5240,
    average: 39.1,
    strikeRate: 136.2,
    cricheroesStats: { 'Dismissals': '190', 'Stumpings': '42', 'Death Over SR': '185.0', 'Trophies': '5' },
  },
  {
    id: 'p_pant',
    name: 'Rishabh Pant',
    role: 'Wicketkeeper',
    basePrice: 200,
    status: 'available',
    previousTeamCode: 'DEL',
    matches: 110,
    runs: 3280,
    average: 35.3,
    strikeRate: 148.5,
    cricheroesStats: { 'Dismissals': '95', 'High Score': '128*', 'Boundary %': '59.2%' },
  },
  {
    id: 'p_klaasen',
    name: 'Heinrich Klaasen',
    role: 'Wicketkeeper',
    basePrice: 150,
    status: 'available',
    previousTeamCode: 'MT',
    matches: 42,
    runs: 1250,
    average: 38.6,
    strikeRate: 168.4,
    cricheroesStats: { 'Spin SR': '192.5', 'Sixes per Innings': '2.6' },
  },
  {
    id: 'p_samson',
    name: 'Sanju Samson',
    role: 'Wicketkeeper',
    basePrice: 150,
    status: 'available',
    previousTeamCode: 'BLR',
    matches: 162,
    runs: 4250,
    average: 30.5,
    strikeRate: 138.9,
    cricheroesStats: { 'Dismissals': '88', 'Centuries': '3', 'High Score': '119' },
  },
  {
    id: 'p_pooran',
    name: 'Nicholas Pooran',
    role: 'Wicketkeeper',
    basePrice: 150,
    status: 'available',
    previousTeamCode: 'CSK',
    matches: 75,
    runs: 1780,
    average: 31.4,
    strikeRate: 155.6,
    cricheroesStats: { 'Sixes': '118', 'Death SR': '188.4' },
  },
  {
    id: 'p_salt',
    name: 'Phil Salt',
    role: 'Wicketkeeper',
    basePrice: 100,
    status: 'available',
    previousTeamCode: 'KKR',
    matches: 35,
    runs: 920,
    average: 32.8,
    strikeRate: 162.1,
    cricheroesStats: { 'Powerplay SR': '175.2', 'Centuries': '2' },
  },
];

export function seedDemoRoom(forceReset = false): {
  roomId: string;
  adminToken: string;
  teams: { id: string; name: string; code: string; token: string; purse: number }[];
  playersCount: number;
} {
  const exists = db.roomExists(DEMO_ROOM_ID);
  if (exists) {
    if (!forceReset) {
      const room = db.loadRoom(DEMO_ROOM_ID);
      if (room) {
        return {
          roomId: DEMO_ROOM_ID,
          adminToken: room.adminToken,
          teams: room.teams.map((t) => ({ id: t.id, name: t.name, code: t.code, token: t.token, purse: t.purse })),
          playersCount: room.players.length,
        };
      }
    }
    // Delete existing room for clean reset
    forgetRoom(DEMO_ROOM_ID, true);
    db.deleteRoom(DEMO_ROOM_ID);
  }

  const rules: AuctionRules = {
    timerSeconds: 15,
    rtmEnabled: true,
    incrementTiers: DEFAULT_RULES.incrementTiers,
  };

  db.createRoom({
    roomId: DEMO_ROOM_ID,
    name: 'Premier Cricket League 2026 (Mega Auction)',
    adminToken: DEMO_ADMIN_TOKEN,
    rules,
    teams: DEMO_TEAMS,
    players: DEMO_PLAYERS,
  });

  return {
    roomId: DEMO_ROOM_ID,
    adminToken: DEMO_ADMIN_TOKEN,
    teams: DEMO_TEAMS.map((t) => ({ id: t.id, name: t.name, code: t.code, token: t.token, purse: t.purse })),
    playersCount: DEMO_PLAYERS.length,
  };
}
